// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLogis.API.Data;

#nullable disable

namespace SmartLogis.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251011213645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartLogis.API.Models.Bitacora", b =>
                {
                    b.Property<int>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBitacora"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBitacora");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Bitacora");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCreationUser")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<int>("IdModificationUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdEstatus");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SmartLogis.API.Models.DetallesEnvio", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionCarga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnvioIdEnvio")
                        .HasColumnType("int");

                    b.Property<int>("IdEnvio")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<int>("IdRuta")
                        .HasColumnType("int");

                    b.Property<int>("IdTransportista")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RutasIdRuta")
                        .HasColumnType("int");

                    b.Property<int?>("TransportistaIdTransportista")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.HasIndex("EnvioIdEnvio");

                    b.HasIndex("IdEnvio");

                    b.HasIndex("IdEstatus");

                    b.HasIndex("IdRuta");

                    b.HasIndex("IdTransportista");

                    b.HasIndex("RutasIdRuta");

                    b.HasIndex("TransportistaIdTransportista");

                    b.ToTable("DetallesEnvio");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Envio", b =>
                {
                    b.Property<int>("IdEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnvio"));

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEntregaEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<string>("NumeroGuia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoEnvio")
                        .HasColumnType("int");

                    b.Property<decimal>("Volumen")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEnvio");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("IdCliente");

                    b.ToTable("Envio");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Estatus", b =>
                {
                    b.Property<int>("IdEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatus"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstatus");

                    b.ToTable("Estatus");
                });

            modelBuilder.Entity("SmartLogis.API.Models.EstatusEnvio", b =>
                {
                    b.Property<int>("IdEstatusEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstatusEnvio"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEnvio")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstatusEnvio");

                    b.HasIndex("IdEnvio");

                    b.ToTable("EstatusEnvio");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Rutas", b =>
                {
                    b.Property<int>("IdRuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRuta"));

                    b.Property<string>("CodigoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistanciaKm")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TiempoEstimadoHoras")
                        .HasColumnType("time");

                    b.HasKey("IdRuta");

                    b.HasIndex("IdEstatus");

                    b.ToTable("Rutas");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Transportista", b =>
                {
                    b.Property<int>("IdTransportista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransportista"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUnidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTransportista");

                    b.HasIndex("IdEstatus");

                    b.ToTable("Transportista");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Bitacora", b =>
                {
                    b.HasOne("SmartLogis.API.Models.Usuario", "Usuario")
                        .WithMany("Bitacora")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Cliente", b =>
                {
                    b.HasOne("SmartLogis.API.Models.Estatus", "Estatus")
                        .WithMany()
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Estatus");
                });

            modelBuilder.Entity("SmartLogis.API.Models.DetallesEnvio", b =>
                {
                    b.HasOne("SmartLogis.API.Models.Envio", null)
                        .WithMany("DetallesEnvio")
                        .HasForeignKey("EnvioIdEnvio");

                    b.HasOne("SmartLogis.API.Models.Envio", "Envio")
                        .WithMany()
                        .HasForeignKey("IdEnvio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartLogis.API.Models.Estatus", "Estatus")
                        .WithMany()
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartLogis.API.Models.Rutas", "Rutas")
                        .WithMany()
                        .HasForeignKey("IdRuta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartLogis.API.Models.Transportista", "Transportista")
                        .WithMany()
                        .HasForeignKey("IdTransportista")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartLogis.API.Models.Rutas", null)
                        .WithMany("DetallesEnvio")
                        .HasForeignKey("RutasIdRuta");

                    b.HasOne("SmartLogis.API.Models.Transportista", null)
                        .WithMany("DetallesEnvio")
                        .HasForeignKey("TransportistaIdTransportista");

                    b.Navigation("Envio");

                    b.Navigation("Estatus");

                    b.Navigation("Rutas");

                    b.Navigation("Transportista");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Envio", b =>
                {
                    b.HasOne("SmartLogis.API.Models.Cliente", null)
                        .WithMany("Envios")
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("SmartLogis.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SmartLogis.API.Models.EstatusEnvio", b =>
                {
                    b.HasOne("SmartLogis.API.Models.Envio", "Envio")
                        .WithMany("EstatusEnvios")
                        .HasForeignKey("IdEnvio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envio");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Rutas", b =>
                {
                    b.HasOne("SmartLogis.API.Models.Estatus", "Estatus")
                        .WithMany()
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Estatus");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Transportista", b =>
                {
                    b.HasOne("SmartLogis.API.Models.Estatus", "Estatus")
                        .WithMany()
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Estatus");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Cliente", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Envio", b =>
                {
                    b.Navigation("DetallesEnvio");

                    b.Navigation("EstatusEnvios");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Rutas", b =>
                {
                    b.Navigation("DetallesEnvio");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Transportista", b =>
                {
                    b.Navigation("DetallesEnvio");
                });

            modelBuilder.Entity("SmartLogis.API.Models.Usuario", b =>
                {
                    b.Navigation("Bitacora");
                });
#pragma warning restore 612, 618
        }
    }
}
